Repository AlexGuillard/Area, pull requests merged in 2023-12, with the labels that each got.

#20 feat(server): empty route signin/signup
  server/src/app.module.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/auth.dto.ts
  server/src/auth/dto/index.ts
Labels: back

#25 feat(DB): 24 setup database
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20231213100006_db/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/auth.dto.ts
  server/src/auth/dto/index.ts
  server/src/main.ts
Labels: DB

#28 feat(11 > main): setup aboutjson route
  .gitignore
  server/src/about/about.controller.spec.ts
  server/src/about/about.controller.ts
  server/src/about/about.module.ts
  server/src/about/about.service.spec.ts
  server/src/about/about.service.ts
  server/src/about/dto/about.dto.ts
  server/src/about/dto/index.ts
  server/src/app.module.ts
Labels: back

#27 ci(web): add linter check
  .github/workflows/checks.yml
  web/package.json
Labels: CI/CD

#32 Complete signin/signup with db
  .gitignore
  server/.env
  server/.env.test
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20231214102643_db/migration.sql
  server/prisma/schema.prisma
  server/src/app.module.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/prisma/prisma.module.ts
  server/src/prisma/prisma.service.ts
Labels: back

#35 feat(12 > main): setup me route
  server/prisma/migrations/20231215142546_db/migration.sql
  server/prisma/schema.prisma
  server/src/app.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/auth.dto.ts
  server/src/me/dto/index.ts
  server/src/me/dto/me.dto.ts
  server/src/me/me.controller.ts
  server/src/me/me.module.ts
  server/src/me/me.service.spec.ts
  server/src/me/me.service.ts
Labels: back

#36 feat(OAuth (22 > main)): Google OAuth 2.0
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/main.ts
  server/src/me/me.controller.ts
  server/src/me/me.module.ts
  server/src/me/me.service.ts
  server/src/prisma/prisma.module.ts
  server/src/prisma/prisma.service.ts
  web/package-lock.json
  web/package.json
  web/src/Component/GoogleButton/GoogleButton.tsx
  web/src/Page/Login/login.tsx
  web/src/hooks/useStore.ts
Labels: web, back

#34 ci(mobile): add linter check
  .github/workflows/checks.yml
Labels: CI/CD

#40 fix(google-params > main): change arguments login google
  server/src/auth/auth.controller.ts
  server/src/auth/dto/index.ts
  server/src/auth/dto/token.dto.ts
Labels: back

#39 feat( Modal edit/add + AddButton (31 > main)): create modal component and AddButton
  web/package-lock.json
  web/package.json
  web/src/Component/Add/add.css
  web/src/Component/Add/add.tsx
  web/src/Component/AddButton/AddButton.css
  web/src/Component/AddButton/AddButton.tsx
  web/src/Component/Edit/edit.css
  web/src/Component/Edit/edit.tsx
  web/src/Component/Modals/Add/Add.tsx
  web/src/Component/Modals/Edit/Edit.tsx
  web/src/Component/Modals/Modal.css
  web/src/Palette.css
Labels: web

#45 feat( GoogleService (38 > main)) create google service
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20231219181616_/migration.sql
  server/prisma/schema.prisma
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/google-auth/dto/google.dto.ts
  server/src/google-auth/google-auth.controller.spec.ts
  server/src/google-auth/google-auth.controller.ts
  server/src/google-auth/google-auth.module.ts
  server/src/google-auth/google-auth.service.spec.ts
  server/src/google-auth/google-auth.service.ts
  server/src/google-auth/google-oauth.guard.ts
  server/src/me/dto/index.ts
  server/src/services/services.controller.ts
  server/src/services/services.module.ts
  server/src/services/services.service.ts
  server/src/strategy/google.strategy.ts
Labels: back

#53 feat(Gmail (46 > main)) create the reaction send mail
  server/package-lock.json
  server/src/app.module.ts
  server/src/mailing/mailing.controller.ts
  server/src/mailing/mailing.module.ts
  server/src/mailing/mailing.service.ts
  server/templates/action.hbs
  web/package-lock.json
Labels: back

#59 feat(GoogleService (56 > main)): add GoogleButton to register
  web/src/Component/GoogleButton/GoogleButton.tsx
  web/src/Page/Register/register.tsx
Labels: web

#60 feat(Reaction route > main): reaction route to work
  server/prisma/migrations/20231220113557_/migration.sql
  server/prisma/migrations/20231221113815_db/migration.sql
  server/prisma/schema.prisma
  server/src/action/action.service.ts
  server/src/app.module.ts
  server/src/area/area.module.ts
  server/src/area/area.service.spec.ts
  server/src/area/area.service.ts
  server/src/area/dto/area.dto.ts
  server/src/reaction/dto/index.ts
  server/src/reaction/dto/reaction.dto.ts
  server/src/reaction/reaction.controller.ts
  server/src/reaction/reaction.module.ts
  server/src/reaction/reaction.service.spec.ts
  server/src/reaction/reaction.service.ts
Labels: back

#72 ci(codecov): add codecov job
  .github/workflows/codecov.yml
  codecov.yml
  server/package.json
Labels: CI/CD

#73 feat(GoogleService / Gmail (61 > main)) refacto reaction mail
  server/prisma/migrations/20231226102328_/migration.sql
  server/src/about/about.service.ts
  server/src/auth/auth.service.ts
  server/src/google-auth/google-auth.controller.ts
  server/src/google-auth/google-oauth.guard.ts
  server/src/mailing/mailing.controller.ts
  server/src/mailing/mailing.module.ts
  server/src/mailing/mailing.service.ts
  server/src/reaction/reaction.module.ts
  server/src/reaction/reaction.service.spec.ts
  server/src/reaction/reaction.service.ts
  server/src/strategy/google.strategy.ts
  temp/GoogleButton/GoogleButton.tsx
Labels: back, service
